
/*********************************************************************************************************
 * Software License Agreement (BSD License)
 * 
 * Copyright 2014 Next Century Corporation. All rights reserved.   
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted
 * provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice, this list of conditions
 * and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions
 * and the following disclaimer in the documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or
 * promote products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT
 * NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.26 at 04:50:49 PM EDT 
//


package com.ncc.sightt.metadata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "modelName",
        "viewAngle",
        "distanceFromCamera",
        "name",
        "objectID",
        "classID",
        "occlusion",
        "polygon",
        "points",
        "objectParts"
})
@XmlRootElement(name = "object")
public class Object {

    @XmlElement(required = true)
    protected String modelName;
    @XmlElement(required = true)
    protected ViewAngle viewAngle;
    @XmlElement(required = true)
    protected DistanceFromCamera distanceFromCamera;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected ObjectID objectID;
    @XmlElement(required = true)
    protected String classID;
    @XmlElement(required = true)
    protected String occlusion;
    @XmlElement(required = true)
    protected Polygon polygon;
    @XmlElement(required = true)
    protected Points points;
    @XmlElement(required = true)
    protected ObjectParts objectParts;

    /**
     * Gets the value of the modelName property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * Sets the value of the modelName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setModelName(String value) {
        this.modelName = value;
    }

    /**
     * Gets the value of the viewAngle property.
     *
     * @return possible object is
     *         {@link ViewAngle }
     */
    public ViewAngle getViewAngle() {
        return viewAngle;
    }

    /**
     * Sets the value of the viewAngle property.
     *
     * @param value allowed object is
     *              {@link ViewAngle }
     */
    public void setViewAngle(ViewAngle value) {
        this.viewAngle = value;
    }

    /**
     * Gets the value of the distanceFromCamera property.
     *
     * @return possible object is
     *         {@link DistanceFromCamera }
     */
    public DistanceFromCamera getDistanceFromCamera() {
        return distanceFromCamera;
    }

    /**
     * Sets the value of the distanceFromCamera property.
     *
     * @param value allowed object is
     *              {@link DistanceFromCamera }
     */
    public void setDistanceFromCamera(DistanceFromCamera value) {
        this.distanceFromCamera = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the objectID property.
     *
     * @return possible object is
     *         {@link ObjectID }
     */
    public ObjectID getObjectID() {
        return objectID;
    }

    /**
     * Sets the value of the objectID property.
     *
     * @param value allowed object is
     *              {@link ObjectID }
     */
    public void setObjectID(ObjectID value) {
        this.objectID = value;
    }

    /**
     * Gets the value of the classID property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getClassID() {
        return classID;
    }

    /**
     * Sets the value of the classID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setClassID(String value) {
        this.classID = value;
    }

    /**
     * Gets the value of the occlusion property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getOcclusion() {
        return occlusion;
    }

    /**
     * Sets the value of the occlusion property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOcclusion(String value) {
        this.occlusion = value;
    }

    /**
     * Gets the value of the polygon property.
     *
     * @return possible object is
     *         {@link Polygon }
     */
    public Polygon getPolygon() {
        return polygon;
    }

    /**
     * Sets the value of the polygon property.
     *
     * @param value allowed object is
     *              {@link Polygon }
     */
    public void setPolygon(Polygon value) {
        this.polygon = value;
    }

    /**
     * Gets the value of the points property.
     *
     * @return possible object is
     *         {@link Points }
     */
    public Points getPoints() {
        return points;
    }

    /**
     * Sets the value of the points property.
     *
     * @param value allowed object is
     *              {@link Points }
     */
    public void setPoints(Points value) {
        this.points = value;
    }

    /**
     * Gets the value of the objectParts property.
     *
     * @return possible object is
     *         {@link ObjectParts }
     */
    public ObjectParts getObjectParts() {
        return objectParts;
    }

    /**
     * Sets the value of the objectParts property.
     *
     * @param value allowed object is
     *              {@link ObjectParts }
     */
    public void setObjectParts(ObjectParts value) {
        this.objectParts = value;
    }

}
